### ISSUE TITLE
CDH: way to define alternative location of the config file?

### ISSUE THREAD

**Issue by mkulke** [confidential-containers/guest-components#489]
At the moment (CCv0) kata-agent launches CDH with no arguments. 

```rust
if let Err(e) = launch_process(
    logger,
    CDH_PATH,
    &vec![],
    CDH_SOCKET,
    DEFAULT_LAUNCH_PROCESS_TIMEOUT,
) ...
```

This means it will attempt to read a default config file at `/etc/confidential-data-hub.toml`. The config file is supposed to be dynamic, i.e. it will be populated at guest launch with values retrieved from init-data.

In a measured rootfs for peerpods `/etc` is on a read-only, dmverity-checked volume. all the dynamic files go into a (memory backed) `/run` folder. (I think this would also be a good pattern independent of how peerpod does it).

I see different ways of addressing this:

- default config path to `/run/confidential-containers/confidential-data-hub.toml` (unintuitive, possibly)
- make the default path for the config file configurable via env `CDH_CONFIG_PATH` (fine IMO, feels a bit weird that we have to do such gymnastics, there is precedent with `KATA_AGENT_CONFIG_PATH`, though)
- do not launch CDH programmatically from agent, but use an init system instead (a comfortable option, a systemd directive can be easily adjusted. I think there were plans for this in the merge-to-main, however since those dynamic values are supposed to be set via agent RPC endpoint I wouldn't know how this works. can someone confirm?)
- instead of (or prior to) defaulting to `offline-fs-kbc` if the config-file is not found, we could fall back to the AA_KBC_PARAMS env (not sure, we probably want to retire that variable).

**Comment by fidencio** [comment]
> * do not launch CDH programmatically from agent, but use an init system instead (a comfortable option, a systemd directive can be easily adjusted. I think there were plans for this in the merge-to-main, however since those dynamic values are supposed to be set via agent RPC endpoint I wouldn't know how this works. can someone confirm?)

Although this would be my preference, we've a lot of folks who don't want to rely on systemd for reasons, and maybe it's time to have the conversation on whether it's worth or not, as it seems that we end up adding a lot of complexity for no good reason.

**Comment by stevenhorsman** [comment]
This is probably way off topic, but once init process comes in would this effect anything? My understanding is that with the current kata-agent driving initProcess/policy endpoint, we need to start the guest-components is a semi-initialised state from kata-agent as we don't have received the initdata from the pod spec when we create the sandbox and kata-agent and then send through the config later and fully initialise it (which feels like weirdness to me, but that's a different issue). If we have a pre-canned config/template that we pass from kata-agent at launch, would that result in the guest-components getting confused and either thinking it's fully initialised in the init-process world, not not fully initialised now? Or is this going to change once we adopt init-data, so not worth trying to predict?

**Comment by fitzthum** [comment]
When it comes to where to find the config file, I don't mind adding an optional env var to override the default location. It's maybe a bit inelegant, but that's easy to implement in the short term.

There are some other things we need to think about regarding config for the guest components, but I think we can consider them separately. The main quirks are probably that some components need to be (partially) configured prior to InitData being received (this is mainly the AA not the CDH) and on some platforms we will need fallback configurations because InitData isn't supported. We've thought about both of these cases already but we should try to document more clearly what the plan is. Like I said, I don't think it really affects this issue.

**Comment by Xynnn007** [comment]
Hi @mkulke To fix this issue I prefer to `CDH_CONFIG_PATH` way rather than  `AA_KBC_PARAMS` way. The former could also help to config the [resource configuration parts](https://github.com/confidential-containers/guest-components/blob/main/confidential-data-hub/hub/src/bin/confidential-data-hub/config.rs#L36-L39), while the latter can only config the remote kbs addr and kbc type.

Thanks @stevenhorsman for sharing your idea upon init system and I also agree that an init system before kata-agent would be a best choice to me now. The current design, s.t.
1. Without systemd
2. Kata-agent handle initdata set request

will result in that a partial initialized component like AA as @fitzthum mentioned. A workaround up to now before initdata is implemented is
1. kata-agent will still launch AA and CDH
2. kata-agent receives initdata, launch CDH and update configuration of AA

With init system solution we can avoid partial initialized state. As for a binary to handle Setinitdata RPC, things could also somehow be simpler, s.t.
1. Use **virtio-fs/9p** from kata-runtime/VMM to mount initdata to a specific path in pod like `/run/confidential-containers/initdata`
2. Launch AA and check the contents under `/run/confidential-containers/initdata` if its integrity is bound to the field in evidence
3. launch kata-agent, CDH, stc.

For scenarios who might not support virtio-fs, probably peer-pod. Still use user-data-processor solution.

**Comment by mkulke** [comment]
Ok, I see a consensus forming around adding `CDH_CONFIG_PATH`  for the time being, until we settle on a lean solution for seeding configuration to CVMs (I hope we don't end up setting it in kata-agent w/ `env::set_var(...)` 🙏)
