### ISSUE TITLE
Crypto | Turn to purely rust stack

### ISSUE THREAD

**Issue by Xynnn007** [confidential-containers/guest-components#520]
Currently, openssl stack cannot be statically link when building while purely rust (based on `ring`) could achieve. This issue comes from some discussion of https://github.com/confidential-containers/guest-components/issues/422.

The directly result is that if we get rid of openssl in image-rs/ocicrypt-rs, we can achieve musl building target for kata-agent.

AA depends underlying gnu-built `.so`s, thus it might not need to support this.

**Comment by fidencio** [comment]
@Xynnn007, I'm just trying to build, for instance, the evidence_getter binary in a static way, and that's not possible on Ubuntu, for instance, because we don't have tss2 static libraries there.

Also, we don't have many options to use different distros as libtdx-attest is not present, for instance, on alpine.

**Comment by fitzthum** [comment]
Building the TDX stuff might get a little bit easier once we have fully adopted the configfs-tsm approach. wdyt @mythi

**Comment by fidencio** [comment]
@fitzthum, good point!

@Xynnn007, also keep in mind that musl support is not the best for s390x and ppc64le.  While ppc64le is not supported by us, s390x is, and will still be using glibc.

**Comment by mythi** [comment]
> Building the TDX stuff might get a little bit easier once we have fully adopted the configfs-tsm approach. wdyt @mythi

Getting rid of `libtdx-attest` is the goal but will take some time still.

**Comment by mythi** [comment]
> Currently, openssl stack cannot be statically link when building while purely rust (based on `ring`) could achieve

I did not think static linking as the main driver here but more about having a unified crypto stack and reduced amount of dependencies. After thinking a bit further, we may have users who prefer to use OS provided crypto libs (i.e., openssl) for TLS etc. due to compliance reasons for example, so dropping the support completely may not be desirable after all.

**Comment by Xynnn007** [comment]
@fidencio Agreed. The advantage of glibc is widely compilable which I like. If we do not have strict need for musl, glibc is the best to me.

Back to the issue, another advantage of replacement is that openssl would make the build process slower (I do not know why everytime I compile the binary, openssl would be compiled again), but `ring` would not.

**Comment by Xynnn007** [comment]
Let's mark this as closed before anyone needs to reopen it.
